# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'fan' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for fan

  pod 'react-native-ble-manager', :path => '../node_modules/react-native-ble-manager'

end
